name: Deploy on GCP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.APPLICATION_CREDENTIALS}}
        with:
          args: builds submit --tag gcr.io/${{secrets.PROJECT_ID}}/fittings
